#ifndef GUARD_CONSTANTS_BATTLE_FRONTIER_H
#define GUARD_CONSTANTS_BATTLE_FRONTIER_H

#define FRONTIER_CHALLENGE(facility, mode) ((facility << 8) + mode)

#define FRONTIER_LVL_50  0
#define FRONTIER_LVL_OPEN 1

#define FRONTIER_MAX_LEVEL_50   50
#define FRONTIER_MIN_LEVEL_OPEN 60
#define FRONTIER_MAX_LEVEL_OPEN MAX_LEVEL

#define FRONTIER_STAGES_PER_CHALLENGE 7

#endif // GUARD_CONSTANTS_BATTLE_FRONTIER_H
