#ifndef GUARD_CONSTANTS_REGIONS_H
#define GUARD_CONSTANTS_REGIONS_H

// Core-series regions
enum Region
{
    REGION_NONE,
    REGION_KANTO,
    REGION_JOHTO,
    REGION_HOENN,
    REGION_SINNOH,
    REGION_UNOVA,
    REGION_KALOS,
    REGION_ALOLA,
    REGION_GALAR,
    REGION_HISUI,
    REGION_PALDEA,
    REGIONS_COUNT,
};

// Convenience macros for script usage
#define KANTO  REGION_KANTO
#define JOHTO  REGION_JOHTO
#define HOENN  REGION_HOENN
#define SINNOH REGION_SINNOH
#define UNOVA  REGION_UNOVA
#define KALOS  REGION_KALOS
#define ALOLA  REGION_ALOLA
#define GALAR  REGION_GALAR
#define HISUI  REGION_HISUI
#define PALDEA REGION_PALDEA

#endif  // GUARD_CONSTANTS_REGIONS_H
