gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is BIRCH.\p"
	.string "But everyone calls me the POKéMON\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
        .string "Hmm… Wait a moment. You're…\p"
        .string "Of course! It's you, {PLAYER}{KUN}!\n"
        .string "My goodness, it's been so many years!\p"
        .string "You've certainly grown! Hardly\n"
        .string "recognized you. I still remember\l"
        .string "when you, BRENDAN, and MAY used to\l"
        .string "chase POKéMON all around LITTLEROOT.\p"
        .string "$"

gText_Birch_AreYouReady::
        .string "Well, I can't keep you here\n"
        .string "reminiscing forever.\p"
        .string "You'll find that HOENN has changed\n"
        .string "quite a bit since you left…\p"
        .string "But we'll have time to catch up soon.\p"
        .string "For now, your very own POKéMON\n"
        .string "adventure awaits!\p"
        .string "$"
