gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is BIRCH.\p"
	.string "But everyone calls me the POKéMON\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
        .string "Ah… so it really is you, {PLAYER}!$"

gText_Birch_EightYears::
        .string "I can't believe it's been eight years\n"
        .string "since you left.$"

gText_Player_StrangeToBeBack::
        .string "Yeah… it feels strange to be back.$"

gText_Birch_RegionChanged::
        .string "HOENN's changed a lot in that time.$"

gText_Birch_WelcomeHome::
        .string "But it's good to have you home,\n"
        .string "{PLAYER}!$"

gText_Birch_JourneyStart::
        .string "Your journey through this changed\n"
        .string "HOENN is just beginning!$"

gText_Birch_AreYouReady::
        .string "Well, I can't keep you here\n"
        .string "reminiscing forever.\p"
        .string "You'll find that HOENN has changed\n"
        .string "quite a bit since you left…\p"
        .string "But we'll have time to catch up soon.\p"
        .string "For now, your very own POKéMON\n"
        .string "adventure awaits!\p"
        .string "$"
