// Autogenerated front pic and palette data for Platinum trainers

const u32 gTrainerFrontPic_DP_Ace_Trainer_DoubleTeam[] = INCBIN_U32("graphics/trainers/front_pics/DP_Ace_Trainer_DoubleTeam.4bpp.smol");
const u16 gTrainerPalette_DP_Ace_Trainer_DoubleTeam[] = INCBIN_U16("graphics/trainers/palettes/DP_Ace_Trainer_DoubleTeam.gbapal");

const u32 gTrainerFrontPic_DP_Ace_Trainer_F[] = INCBIN_U32("graphics/trainers/front_pics/DP_Ace_Trainer_F.4bpp.smol");
const u16 gTrainerPalette_DP_Ace_Trainer_F[] = INCBIN_U16("graphics/trainers/palettes/DP_Ace_Trainer_F.gbapal");

const u32 gTrainerFrontPic_DP_Ace_Trainer_M[] = INCBIN_U32("graphics/trainers/front_pics/DP_Ace_Trainer_M.4bpp.smol");
const u16 gTrainerPalette_DP_Ace_Trainer_M[] = INCBIN_U16("graphics/trainers/palettes/DP_Ace_Trainer_M.gbapal");

const u32 gTrainerFrontPic_DP_Ace_Trainer_Snow_F[] = INCBIN_U32("graphics/trainers/front_pics/DP_Ace_Trainer_Snow_F.4bpp.smol");
const u16 gTrainerPalette_DP_Ace_Trainer_Snow_F[] = INCBIN_U16("graphics/trainers/palettes/DP_Ace_Trainer_Snow_F.gbapal");

const u32 gTrainerFrontPic_DP_Ace_Trainer_Snow_M[] = INCBIN_U32("graphics/trainers/front_pics/DP_Ace_Trainer_Snow_M.4bpp.smol");
const u16 gTrainerPalette_DP_Ace_Trainer_Snow_M[] = INCBIN_U16("graphics/trainers/palettes/DP_Ace_Trainer_Snow_M.gbapal");

const u32 gTrainerFrontPic_DP_Aroma_Lady[] = INCBIN_U32("graphics/trainers/front_pics/DP_Aroma_Lady.4bpp.smol");
const u16 gTrainerPalette_DP_Aroma_Lady[] = INCBIN_U16("graphics/trainers/palettes/DP_Aroma_Lady.gbapal");

const u32 gTrainerFrontPic_DP_Barry[] = INCBIN_U32("graphics/trainers/front_pics/DP_Barry.4bpp.smol");
const u16 gTrainerPalette_DP_Barry[] = INCBIN_U16("graphics/trainers/palettes/DP_Barry.gbapal");

const u32 gTrainerFrontPic_DP_Battle_Girl[] = INCBIN_U32("graphics/trainers/front_pics/DP_Battle_Girl.4bpp.smol");
const u16 gTrainerPalette_DP_Battle_Girl[] = INCBIN_U16("graphics/trainers/palettes/DP_Battle_Girl.gbapal");

const u32 gTrainerFrontPic_DP_Beauty[] = INCBIN_U32("graphics/trainers/front_pics/DP_Beauty.4bpp.smol");
const u16 gTrainerPalette_DP_Beauty[] = INCBIN_U16("graphics/trainers/palettes/DP_Beauty.gbapal");

const u32 gTrainerFrontPic_DP_Bertha[] = INCBIN_U32("graphics/trainers/front_pics/DP_Bertha.4bpp.smol");
const u16 gTrainerPalette_DP_Bertha[] = INCBIN_U16("graphics/trainers/palettes/DP_Bertha.gbapal");

const u32 gTrainerFrontPic_DP_Bird_Keeper[] = INCBIN_U32("graphics/trainers/front_pics/DP_Bird_Keeper.4bpp.smol");
const u16 gTrainerPalette_DP_Bird_Keeper[] = INCBIN_U16("graphics/trainers/palettes/DP_Bird_Keeper.gbapal");

const u32 gTrainerFrontPic_DP_Black_Belt[] = INCBIN_U32("graphics/trainers/front_pics/DP_Black_Belt.4bpp.smol");
const u16 gTrainerPalette_DP_Black_Belt[] = INCBIN_U16("graphics/trainers/palettes/DP_Black_Belt.gbapal");

const u32 gTrainerFrontPic_DP_Breeder_F[] = INCBIN_U32("graphics/trainers/front_pics/DP_Breeder_F.4bpp.smol");
const u16 gTrainerPalette_DP_Breeder_F[] = INCBIN_U16("graphics/trainers/palettes/DP_Breeder_F.gbapal");

const u32 gTrainerFrontPic_DP_Breeder_M[] = INCBIN_U32("graphics/trainers/front_pics/DP_Breeder_M.4bpp.smol");
const u16 gTrainerPalette_DP_Breeder_M[] = INCBIN_U16("graphics/trainers/palettes/DP_Breeder_M.gbapal");

const u32 gTrainerFrontPic_DP_Buck[] = INCBIN_U32("graphics/trainers/front_pics/DP_Buck.4bpp.smol");
const u16 gTrainerPalette_DP_Buck[] = INCBIN_U16("graphics/trainers/palettes/DP_Buck.gbapal");

const u32 gTrainerFrontPic_DP_Bug_Catcher[] = INCBIN_U32("graphics/trainers/front_pics/DP_Bug_Catcher.4bpp.smol");
const u16 gTrainerPalette_DP_Bug_Catcher[] = INCBIN_U16("graphics/trainers/palettes/DP_Bug_Catcher.gbapal");

const u32 gTrainerFrontPic_DP_Byron[] = INCBIN_U32("graphics/trainers/front_pics/DP_Byron.4bpp.smol");
const u16 gTrainerPalette_DP_Byron[] = INCBIN_U16("graphics/trainers/palettes/DP_Byron.gbapal");

const u32 gTrainerFrontPic_DP_Cameraman[] = INCBIN_U32("graphics/trainers/front_pics/DP_Cameraman.4bpp.smol");
const u16 gTrainerPalette_DP_Cameraman[] = INCBIN_U16("graphics/trainers/palettes/DP_Cameraman.gbapal");

const u32 gTrainerFrontPic_DP_Camper[] = INCBIN_U32("graphics/trainers/front_pics/DP_Camper.4bpp.smol");
const u16 gTrainerPalette_DP_Camper[] = INCBIN_U16("graphics/trainers/palettes/DP_Camper.gbapal");

const u32 gTrainerFrontPic_DP_Candice[] = INCBIN_U32("graphics/trainers/front_pics/DP_Candice.4bpp.smol");
const u16 gTrainerPalette_DP_Candice[] = INCBIN_U16("graphics/trainers/palettes/DP_Candice.gbapal");

const u32 gTrainerFrontPic_DP_Cheryl[] = INCBIN_U32("graphics/trainers/front_pics/DP_Cheryl.4bpp.smol");
const u16 gTrainerPalette_DP_Cheryl[] = INCBIN_U16("graphics/trainers/palettes/DP_Cheryl.gbapal");

const u32 gTrainerFrontPic_DP_Clown[] = INCBIN_U32("graphics/trainers/front_pics/DP_Clown.4bpp.smol");
const u16 gTrainerPalette_DP_Clown[] = INCBIN_U16("graphics/trainers/palettes/DP_Clown.gbapal");

const u32 gTrainerFrontPic_DP_Collector[] = INCBIN_U32("graphics/trainers/front_pics/DP_Collector.4bpp.smol");
const u16 gTrainerPalette_DP_Collector[] = INCBIN_U16("graphics/trainers/palettes/DP_Collector.gbapal");

const u32 gTrainerFrontPic_DP_Cowgirl[] = INCBIN_U32("graphics/trainers/front_pics/DP_Cowgirl.4bpp.smol");
const u16 gTrainerPalette_DP_Cowgirl[] = INCBIN_U16("graphics/trainers/palettes/DP_Cowgirl.gbapal");

const u32 gTrainerFrontPic_DP_Crasher_Wake[] = INCBIN_U32("graphics/trainers/front_pics/DP_Crasher_Wake.4bpp.smol");
const u16 gTrainerPalette_DP_Crasher_Wake[] = INCBIN_U16("graphics/trainers/palettes/DP_Crasher_Wake.gbapal");

const u32 gTrainerFrontPic_DP_Cyclist_F[] = INCBIN_U32("graphics/trainers/front_pics/DP_Cyclist_F.4bpp.smol");
const u16 gTrainerPalette_DP_Cyclist_F[] = INCBIN_U16("graphics/trainers/palettes/DP_Cyclist_F.gbapal");

const u32 gTrainerFrontPic_DP_Cyclist_M[] = INCBIN_U32("graphics/trainers/front_pics/DP_Cyclist_M.4bpp.smol");
const u16 gTrainerPalette_DP_Cyclist_M[] = INCBIN_U16("graphics/trainers/palettes/DP_Cyclist_M.gbapal");

const u32 gTrainerFrontPic_DP_Cynthia[] = INCBIN_U32("graphics/trainers/front_pics/DP_Cynthia.4bpp.smol");
const u16 gTrainerPalette_DP_Cynthia[] = INCBIN_U16("graphics/trainers/palettes/DP_Cynthia.gbapal");

const u32 gTrainerFrontPic_DP_Cyrus[] = INCBIN_U32("graphics/trainers/front_pics/DP_Cyrus.4bpp.smol");
const u16 gTrainerPalette_DP_Cyrus[] = INCBIN_U16("graphics/trainers/palettes/DP_Cyrus.gbapal");

const u32 gTrainerFrontPic_DP_Dragon_Tamer[] = INCBIN_U32("graphics/trainers/front_pics/DP_Dragon_Tamer.4bpp.smol");
const u16 gTrainerPalette_DP_Dragon_Tamer[] = INCBIN_U16("graphics/trainers/palettes/DP_Dragon_Tamer.gbapal");

const u32 gTrainerFrontPic_DP_Fantina[] = INCBIN_U32("graphics/trainers/front_pics/DP_Fantina.4bpp.smol");
const u16 gTrainerPalette_DP_Fantina[] = INCBIN_U16("graphics/trainers/palettes/DP_Fantina.gbapal");

const u32 gTrainerFrontPic_DP_Fisherman[] = INCBIN_U32("graphics/trainers/front_pics/DP_Fisherman.4bpp.smol");
const u16 gTrainerPalette_DP_Fisherman[] = INCBIN_U16("graphics/trainers/palettes/DP_Fisherman.gbapal");

const u32 gTrainerFrontPic_DP_Galactic_Grunt_Duo_MM[] = INCBIN_U32("graphics/trainers/front_pics/DP_Galactic_Grunt_Duo_MM.4bpp.smol");
const u16 gTrainerPalette_DP_Galactic_Grunt_Duo_MM[] = INCBIN_U16("graphics/trainers/palettes/DP_Galactic_Grunt_Duo_MM.gbapal");

const u32 gTrainerFrontPic_DP_Galactic_Grunt_F[] = INCBIN_U32("graphics/trainers/front_pics/DP_Galactic_Grunt_F.4bpp.smol");
const u16 gTrainerPalette_DP_Galactic_Grunt_F[] = INCBIN_U16("graphics/trainers/palettes/DP_Galactic_Grunt_F.gbapal");

const u32 gTrainerFrontPic_DP_Galactic_Grunt_M[] = INCBIN_U32("graphics/trainers/front_pics/DP_Galactic_Grunt_M.4bpp.smol");
const u16 gTrainerPalette_DP_Galactic_Grunt_M[] = INCBIN_U16("graphics/trainers/palettes/DP_Galactic_Grunt_M.gbapal");

const u32 gTrainerFrontPic_DP_Gambler[] = INCBIN_U32("graphics/trainers/front_pics/DP_Gambler.4bpp.smol");
const u16 gTrainerPalette_DP_Gambler[] = INCBIN_U16("graphics/trainers/palettes/DP_Gambler.gbapal");

const u32 gTrainerFrontPic_DP_Gardenia[] = INCBIN_U32("graphics/trainers/front_pics/DP_Gardenia.4bpp.smol");
const u16 gTrainerPalette_DP_Gardenia[] = INCBIN_U16("graphics/trainers/palettes/DP_Gardenia.gbapal");

const u32 gTrainerFrontPic_DP_Gentleman[] = INCBIN_U32("graphics/trainers/front_pics/DP_Gentleman.4bpp.smol");
const u16 gTrainerPalette_DP_Gentleman[] = INCBIN_U16("graphics/trainers/palettes/DP_Gentleman.gbapal");

const u32 gTrainerFrontPic_DP_Hiker[] = INCBIN_U32("graphics/trainers/front_pics/DP_Hiker.4bpp.smol");
const u16 gTrainerPalette_DP_Hiker[] = INCBIN_U16("graphics/trainers/palettes/DP_Hiker.gbapal");

const u32 gTrainerFrontPic_DP_Idol[] = INCBIN_U32("graphics/trainers/front_pics/DP_Idol.4bpp.smol");
const u16 gTrainerPalette_DP_Idol[] = INCBIN_U16("graphics/trainers/palettes/DP_Idol.gbapal");

const u32 gTrainerFrontPic_DP_Interviewers[] = INCBIN_U32("graphics/trainers/front_pics/DP_Interviewers.4bpp.smol");
const u16 gTrainerPalette_DP_Interviewers[] = INCBIN_U16("graphics/trainers/palettes/DP_Interviewers.gbapal");

const u32 gTrainerFrontPic_DP_Jogger[] = INCBIN_U32("graphics/trainers/front_pics/DP_Jogger.4bpp.smol");
const u16 gTrainerPalette_DP_Jogger[] = INCBIN_U16("graphics/trainers/palettes/DP_Jogger.gbapal");

const u32 gTrainerFrontPic_DP_Jupiter[] = INCBIN_U32("graphics/trainers/front_pics/DP_Jupiter.4bpp.smol");
const u16 gTrainerPalette_DP_Jupiter[] = INCBIN_U16("graphics/trainers/palettes/DP_Jupiter.gbapal");

const u32 gTrainerFrontPic_DP_Lady[] = INCBIN_U32("graphics/trainers/front_pics/DP_Lady.4bpp.smol");
const u16 gTrainerPalette_DP_Lady[] = INCBIN_U16("graphics/trainers/palettes/DP_Lady.gbapal");

const u32 gTrainerFrontPic_DP_Lass[] = INCBIN_U32("graphics/trainers/front_pics/DP_Lass.4bpp.smol");
const u16 gTrainerPalette_DP_Lass[] = INCBIN_U16("graphics/trainers/palettes/DP_Lass.gbapal");

const u32 gTrainerFrontPic_DP_Lucian[] = INCBIN_U32("graphics/trainers/front_pics/DP_Lucian.4bpp.smol");
const u16 gTrainerPalette_DP_Lucian[] = INCBIN_U16("graphics/trainers/palettes/DP_Lucian.gbapal");

const u32 gTrainerFrontPic_DP_Marley[] = INCBIN_U32("graphics/trainers/front_pics/DP_Marley.4bpp.smol");
const u16 gTrainerPalette_DP_Marley[] = INCBIN_U16("graphics/trainers/palettes/DP_Marley.gbapal");

const u32 gTrainerFrontPic_DP_Mars[] = INCBIN_U32("graphics/trainers/front_pics/DP_Mars.4bpp.smol");
const u16 gTrainerPalette_DP_Mars[] = INCBIN_U16("graphics/trainers/palettes/DP_Mars.gbapal");

const u32 gTrainerFrontPic_DP_Maylene[] = INCBIN_U32("graphics/trainers/front_pics/DP_Maylene.4bpp.smol");
const u16 gTrainerPalette_DP_Maylene[] = INCBIN_U16("graphics/trainers/palettes/DP_Maylene.gbapal");

const u32 gTrainerFrontPic_DP_Mira[] = INCBIN_U32("graphics/trainers/front_pics/DP_Mira.4bpp.smol");
const u16 gTrainerPalette_DP_Mira[] = INCBIN_U16("graphics/trainers/palettes/DP_Mira.gbapal");

const u32 gTrainerFrontPic_DP_Ninja_Boy[] = INCBIN_U32("graphics/trainers/front_pics/DP_Ninja_Boy.4bpp.smol");
const u16 gTrainerPalette_DP_Ninja_Boy[] = INCBIN_U16("graphics/trainers/palettes/DP_Ninja_Boy.gbapal");

const u32 gTrainerFrontPic_DP_Officer[] = INCBIN_U32("graphics/trainers/front_pics/DP_Officer.4bpp.smol");
const u16 gTrainerPalette_DP_Officer[] = INCBIN_U16("graphics/trainers/palettes/DP_Officer.gbapal");

const u32 gTrainerFrontPic_DP_Painter_Artist[] = INCBIN_U32("graphics/trainers/front_pics/DP_Painter_Artist.4bpp.smol");
const u16 gTrainerPalette_DP_Painter_Artist[] = INCBIN_U16("graphics/trainers/palettes/DP_Painter_Artist.gbapal");

const u32 gTrainerFrontPic_DP_Palmer[] = INCBIN_U32("graphics/trainers/front_pics/DP_Palmer.4bpp.smol");
const u16 gTrainerPalette_DP_Palmer[] = INCBIN_U16("graphics/trainers/palettes/DP_Palmer.gbapal");

const u32 gTrainerFrontPic_DP_Parasol_Lady[] = INCBIN_U32("graphics/trainers/front_pics/DP_Parasol_Lady.4bpp.smol");
const u16 gTrainerPalette_DP_Parasol_Lady[] = INCBIN_U16("graphics/trainers/palettes/DP_Parasol_Lady.gbapal");

const u32 gTrainerFrontPic_DP_Picnicker[] = INCBIN_U32("graphics/trainers/front_pics/DP_Picnicker.4bpp.smol");
const u16 gTrainerPalette_DP_Picnicker[] = INCBIN_U16("graphics/trainers/palettes/DP_Picnicker.gbapal");

const u32 gTrainerFrontPic_DP_Poke_Kid[] = INCBIN_U32("graphics/trainers/front_pics/DP_Poke_Kid.4bpp.smol");
const u16 gTrainerPalette_DP_Poke_Kid[] = INCBIN_U16("graphics/trainers/palettes/DP_Poke_Kid.gbapal");

const u32 gTrainerFrontPic_DP_Pokefan_F[] = INCBIN_U32("graphics/trainers/front_pics/DP_Pokefan_F.4bpp.smol");
const u16 gTrainerPalette_DP_Pokefan_F[] = INCBIN_U16("graphics/trainers/palettes/DP_Pokefan_F.gbapal");

const u32 gTrainerFrontPic_DP_Pokefan_M[] = INCBIN_U32("graphics/trainers/front_pics/DP_Pokefan_M.4bpp.smol");
const u16 gTrainerPalette_DP_Pokefan_M[] = INCBIN_U16("graphics/trainers/palettes/DP_Pokefan_M.gbapal");

const u32 gTrainerFrontPic_DP_Pokemon_Ranger_F[] = INCBIN_U32("graphics/trainers/front_pics/DP_Pokemon_Ranger_F.4bpp.smol");
const u16 gTrainerPalette_DP_Pokemon_Ranger_F[] = INCBIN_U16("graphics/trainers/palettes/DP_Pokemon_Ranger_F.gbapal");

const u32 gTrainerFrontPic_DP_Pokemon_Ranger_M[] = INCBIN_U32("graphics/trainers/front_pics/DP_Pokemon_Ranger_M.4bpp.smol");
const u16 gTrainerPalette_DP_Pokemon_Ranger_M[] = INCBIN_U16("graphics/trainers/palettes/DP_Pokemon_Ranger_M.gbapal");

const u32 gTrainerFrontPic_DP_Psychic_F[] = INCBIN_U32("graphics/trainers/front_pics/DP_Psychic_F.4bpp.smol");
const u16 gTrainerPalette_DP_Psychic_F[] = INCBIN_U16("graphics/trainers/palettes/DP_Psychic_F.gbapal");

const u32 gTrainerFrontPic_DP_Psychic_M[] = INCBIN_U32("graphics/trainers/front_pics/DP_Psychic_M.4bpp.smol");
const u16 gTrainerPalette_DP_Psychic_M[] = INCBIN_U16("graphics/trainers/palettes/DP_Psychic_M.gbapal");

const u32 gTrainerFrontPic_DP_Rancher[] = INCBIN_U32("graphics/trainers/front_pics/DP_Rancher.4bpp.smol");
const u16 gTrainerPalette_DP_Rancher[] = INCBIN_U16("graphics/trainers/palettes/DP_Rancher.gbapal");

const u32 gTrainerFrontPic_DP_Rancher_Duo_Belle_and_Pa[] = INCBIN_U32("graphics/trainers/front_pics/DP_Rancher_Duo_Belle_and_Pa.4bpp.smol");
const u16 gTrainerPalette_DP_Rancher_Duo_Belle_and_Pa[] = INCBIN_U16("graphics/trainers/palettes/DP_Rancher_Duo_Belle_and_Pa.gbapal");

const u32 gTrainerFrontPic_DP_Reporter[] = INCBIN_U32("graphics/trainers/front_pics/DP_Reporter.4bpp.smol");
const u16 gTrainerPalette_DP_Reporter[] = INCBIN_U16("graphics/trainers/palettes/DP_Reporter.gbapal");

const u32 gTrainerFrontPic_DP_Rich_Boy[] = INCBIN_U32("graphics/trainers/front_pics/DP_Rich_Boy.4bpp.smol");
const u16 gTrainerPalette_DP_Rich_Boy[] = INCBIN_U16("graphics/trainers/palettes/DP_Rich_Boy.gbapal");

const u32 gTrainerFrontPic_DP_Riley[] = INCBIN_U32("graphics/trainers/front_pics/DP_Riley.4bpp.smol");
const u16 gTrainerPalette_DP_Riley[] = INCBIN_U16("graphics/trainers/palettes/DP_Riley.gbapal");

const u32 gTrainerFrontPic_DP_Roark[] = INCBIN_U32("graphics/trainers/front_pics/DP_Roark.4bpp.smol");
const u16 gTrainerPalette_DP_Roark[] = INCBIN_U16("graphics/trainers/palettes/DP_Roark.gbapal");

const u32 gTrainerFrontPic_DP_Rocker_Guitarist[] = INCBIN_U32("graphics/trainers/front_pics/DP_Rocker_Guitarist.4bpp.smol");
const u16 gTrainerPalette_DP_Rocker_Guitarist[] = INCBIN_U16("graphics/trainers/palettes/DP_Rocker_Guitarist.gbapal");

const u32 gTrainerFrontPic_DP_Roughneck[] = INCBIN_U32("graphics/trainers/front_pics/DP_Roughneck.4bpp.smol");
const u16 gTrainerPalette_DP_Roughneck[] = INCBIN_U16("graphics/trainers/palettes/DP_Roughneck.gbapal");

const u32 gTrainerFrontPic_DP_Ruin_Maniac[] = INCBIN_U32("graphics/trainers/front_pics/DP_Ruin_Maniac.4bpp.smol");
const u16 gTrainerPalette_DP_Ruin_Maniac[] = INCBIN_U16("graphics/trainers/palettes/DP_Ruin_Maniac.gbapal");

const u32 gTrainerFrontPic_DP_Sailor[] = INCBIN_U32("graphics/trainers/front_pics/DP_Sailor.4bpp.smol");
const u16 gTrainerPalette_DP_Sailor[] = INCBIN_U16("graphics/trainers/palettes/DP_Sailor.gbapal");

const u32 gTrainerFrontPic_DP_Saturn[] = INCBIN_U32("graphics/trainers/front_pics/DP_Saturn.4bpp.smol");
const u16 gTrainerPalette_DP_Saturn[] = INCBIN_U16("graphics/trainers/palettes/DP_Saturn.gbapal");

const u32 gTrainerFrontPic_DP_School_Kid_F[] = INCBIN_U32("graphics/trainers/front_pics/DP_School_Kid_F.4bpp.smol");
const u16 gTrainerPalette_DP_School_Kid_F[] = INCBIN_U16("graphics/trainers/palettes/DP_School_Kid_F.gbapal");

const u32 gTrainerFrontPic_DP_School_Kid_M[] = INCBIN_U32("graphics/trainers/front_pics/DP_School_Kid_M.4bpp.smol");
const u16 gTrainerPalette_DP_School_Kid_M[] = INCBIN_U16("graphics/trainers/palettes/DP_School_Kid_M.gbapal");

const u32 gTrainerFrontPic_DP_Scientist[] = INCBIN_U32("graphics/trainers/front_pics/DP_Scientist.4bpp.smol");
const u16 gTrainerPalette_DP_Scientist[] = INCBIN_U16("graphics/trainers/palettes/DP_Scientist.gbapal");

const u32 gTrainerFrontPic_DP_Skier_F[] = INCBIN_U32("graphics/trainers/front_pics/DP_Skier_F.4bpp.smol");
const u16 gTrainerPalette_DP_Skier_F[] = INCBIN_U16("graphics/trainers/palettes/DP_Skier_F.gbapal");

const u32 gTrainerFrontPic_DP_Skier_M[] = INCBIN_U32("graphics/trainers/front_pics/DP_Skier_M.4bpp.smol");
const u16 gTrainerPalette_DP_Skier_M[] = INCBIN_U16("graphics/trainers/palettes/DP_Skier_M.gbapal");

const u32 gTrainerFrontPic_DP_Socialite[] = INCBIN_U32("graphics/trainers/front_pics/DP_Socialite.4bpp.smol");
const u16 gTrainerPalette_DP_Socialite[] = INCBIN_U16("graphics/trainers/palettes/DP_Socialite.gbapal");

const u32 gTrainerFrontPic_DP_Swimmer_F[] = INCBIN_U32("graphics/trainers/front_pics/DP_Swimmer_F.4bpp.smol");
const u16 gTrainerPalette_DP_Swimmer_F[] = INCBIN_U16("graphics/trainers/palettes/DP_Swimmer_F.gbapal");

const u32 gTrainerFrontPic_DP_Swimmer_M[] = INCBIN_U32("graphics/trainers/front_pics/DP_Swimmer_M.4bpp.smol");
const u16 gTrainerPalette_DP_Swimmer_M[] = INCBIN_U16("graphics/trainers/palettes/DP_Swimmer_M.gbapal");

const u32 gTrainerFrontPic_DP_Tuber_F[] = INCBIN_U32("graphics/trainers/front_pics/DP_Tuber_F.4bpp.smol");
const u16 gTrainerPalette_DP_Tuber_F[] = INCBIN_U16("graphics/trainers/palettes/DP_Tuber_F.gbapal");

const u32 gTrainerFrontPic_DP_Tuber_M[] = INCBIN_U32("graphics/trainers/front_pics/DP_Tuber_M.4bpp.smol");
const u16 gTrainerPalette_DP_Tuber_M[] = INCBIN_U16("graphics/trainers/palettes/DP_Tuber_M.gbapal");

const u32 gTrainerFrontPic_DP_Twins[] = INCBIN_U32("graphics/trainers/front_pics/DP_Twins.4bpp.smol");
const u16 gTrainerPalette_DP_Twins[] = INCBIN_U16("graphics/trainers/palettes/DP_Twins.gbapal");

const u32 gTrainerFrontPic_DP_Veteran[] = INCBIN_U32("graphics/trainers/front_pics/DP_Veteran.4bpp.smol");
const u16 gTrainerPalette_DP_Veteran[] = INCBIN_U16("graphics/trainers/palettes/DP_Veteran.gbapal");

const u32 gTrainerFrontPic_DP_Volkner[] = INCBIN_U32("graphics/trainers/front_pics/DP_Volkner.4bpp.smol");
const u16 gTrainerPalette_DP_Volkner[] = INCBIN_U16("graphics/trainers/palettes/DP_Volkner.gbapal");

const u32 gTrainerFrontPic_DP_Waiter[] = INCBIN_U32("graphics/trainers/front_pics/DP_Waiter.4bpp.smol");
const u16 gTrainerPalette_DP_Waiter[] = INCBIN_U16("graphics/trainers/palettes/DP_Waiter.gbapal");

const u32 gTrainerFrontPic_DP_Waitress[] = INCBIN_U32("graphics/trainers/front_pics/DP_Waitress.4bpp.smol");
const u16 gTrainerPalette_DP_Waitress[] = INCBIN_U16("graphics/trainers/palettes/DP_Waitress.gbapal");

const u32 gTrainerFrontPic_DP_Worker[] = INCBIN_U32("graphics/trainers/front_pics/DP_Worker.4bpp.smol");
const u16 gTrainerPalette_DP_Worker[] = INCBIN_U16("graphics/trainers/palettes/DP_Worker.gbapal");

const u32 gTrainerFrontPic_DP_Young_Couple[] = INCBIN_U32("graphics/trainers/front_pics/DP_Young_Couple.4bpp.smol");
const u16 gTrainerPalette_DP_Young_Couple[] = INCBIN_U16("graphics/trainers/palettes/DP_Young_Couple.gbapal");

const u32 gTrainerFrontPic_DP_Youngster[] = INCBIN_U32("graphics/trainers/front_pics/DP_Youngster.4bpp.smol");
const u16 gTrainerPalette_DP_Youngster[] = INCBIN_U16("graphics/trainers/palettes/DP_Youngster.gbapal");

